// Regenerates src/analysisPrompt.js from the v4 prompt + schema.
//
//   node scripts/embed-prompt.mjs
//
// The prompt has exactly one home — ../v4-analysis-prompt.md — and this script
// is the only thing that copies it. Editing src/analysisPrompt.js by hand
// creates a second version of the prompt that will win by accident in whichever
// session happens to read it.
//
// It also emits TOOL_INPUT_SCHEMA: the v4 output schema with $refs inlined and
// the JSON Schema keywords the Messages API's structured outputs do not accept
// stripped (maxLength/minLength/pattern/min-max/minItems/maxItems). Those
// limits are not lost — the validator enforces the ones that matter, and it
// enforces them after the model emits, which is where v4 says they belong.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const source = join(root, '..');

const PROMPT_PATH = join(source, 'v4-analysis-prompt.md');
const SCHEMA_PATH = join(source, 'v4-output-schema.json');

const UNSUPPORTED = new Set([
  'maxLength', 'minLength', 'pattern', 'minimum', 'maximum',
  'exclusiveMinimum', 'exclusiveMaximum', 'multipleOf',
  'minItems', 'maxItems', 'uniqueItems', 'default', 'examples',
  '$schema', 'title',
]);

function sanitize(node, defs, seen = 0) {
  if (seen > 40) throw new Error('schema nesting too deep — recursive $ref?');
  if (Array.isArray(node)) return node.map((n) => sanitize(n, defs, seen + 1));
  if (node === null || typeof node !== 'object') return node;

  if (typeof node.$ref === 'string') {
    const path = node.$ref.replace(/^#\//, '').split('/');
    let target = { definitions: defs };
    for (const seg of path) target = target[seg];
    if (!target) throw new Error(`unresolvable $ref ${node.$ref}`);
    const merged = { ...target, ...node };
    delete merged.$ref;
    return sanitize(merged, defs, seen + 1);
  }

  const out = {};
  for (const [k, v] of Object.entries(node)) {
    if (UNSUPPORTED.has(k)) continue;
    out[k] = sanitize(v, defs, seen + 1);
  }
  // Structured outputs require additionalProperties:false on every object.
  if (out.type === 'object' || (Array.isArray(out.type) && out.type.includes('object')) || out.properties) {
    out.additionalProperties = false;
  }
  return out;
}

const promptMd = readFileSync(PROMPT_PATH, 'utf8');
const schema = JSON.parse(readFileSync(SCHEMA_PATH, 'utf8'));
const defs = schema.definitions || {};
const flat = sanitize({ ...schema, definitions: undefined }, defs);
delete flat.definitions;

const banner = '// AUTO-GENERATED by scripts/embed-prompt.mjs from ../v4-analysis-prompt.md + ../v4-output-schema.json.\n// Do not hand-edit: re-run the script instead.\n';
const body =
  `${banner}\nexport const ANALYSIS_PROMPT = ${JSON.stringify(promptMd)};\n\n` +
  `export const PROMPT_VERSION = 'v4';\n\n` +
  `export const TOOL_INPUT_SCHEMA = ${JSON.stringify(flat, null, 2)};\n`;

writeFileSync(join(root, 'src', 'analysisPrompt.js'), body);
console.log(
  `wrote src/analysisPrompt.js — prompt ${promptMd.length} chars, schema ${JSON.stringify(flat).length} chars`,
);
