// Generated by build-data.cjs from Study 07's work-data.js, plus hand facts
// from Studies 04 (Klydo · branding), 05 (experiment stages, Metro Museum) and
// 06 (Klydo's client page). The prototype's templates read only this and rounds.js.
globalThis.SITE = {
 "pills": [
  {
   "id": "brand",
   "label": "Brand & Identity"
  },
  {
   "id": "web",
   "label": "Website & Product"
  },
  {
   "id": "strategy",
   "label": "Strategy"
  },
  {
   "id": "story",
   "label": "Storytelling"
  },
  {
   "id": "exp",
   "label": "Experiments"
  }
 ],
 "pieces": [
  {
   "pill": "brand",
   "client": "Klydo",
   "piece": "branding",
   "s": "For Klydo, we built the brand for a 15-minute fashion-delivery startup, from name to launch, while the company went from four people to a million orders.",
   "tags": [
    "branding",
    "identity",
    "client work"
   ],
   "url": "/work/klydo/branding.html",
   "have": "partial",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "klydo/branding",
   "clientSlug": "klydo"
  },
  {
   "pill": "brand",
   "client": "Secret Senses",
   "piece": "identity + packaging",
   "s": "For Secret Senses, we drew the identity, illustrations and packaging for an Indian hair-care brand.",
   "tags": [
    "identity",
    "packaging",
    "illustration",
    "client work"
   ],
   "url": "/work/secret-senses/identity-packaging.html",
   "have": "page",
   "to": "piece",
   "clientPage": false,
   "soon": false,
   "slug": "secret-senses/identity-packaging",
   "clientSlug": "secret-senses"
  },
  {
   "pill": "brand",
   "client": "Tatsam",
   "piece": "brand",
   "s": "For Tatsam, we built the brand of a workplace-wellbeing company around one belief: grow people's strengths, don't catalogue their deficits.",
   "tags": [
    "branding",
    "client work"
   ],
   "url": "/work/tatsam/brand.html",
   "have": "page",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "tatsam/brand",
   "clientSlug": "tatsam"
  },
  {
   "pill": "brand",
   "client": "Gliitch",
   "piece": "identity",
   "s": "For Gliitch, we made a vibrant identity for a Hong Kong digital provider to small restaurants.",
   "tags": [
    "identity",
    "client work"
   ],
   "url": "/work/gliitch/identity.html",
   "have": "page",
   "to": "piece",
   "clientPage": false,
   "soon": false,
   "slug": "gliitch/identity",
   "clientSlug": "gliitch"
  },
  {
   "pill": "brand",
   "client": "XTDB",
   "piece": "visual identity",
   "s": "For XTDB, we gave a time-focused database a visual identity that could sit next to the engineering.",
   "tags": [
    "identity",
    "client work"
   ],
   "url": "/work/xtdb/visual-identity.html",
   "have": "page",
   "to": "piece",
   "clientPage": false,
   "soon": false,
   "slug": "xtdb/visual-identity",
   "clientSlug": "xtdb"
  },
  {
   "pill": "brand",
   "client": "Agemo / Codewords",
   "piece": "brand voice",
   "s": "For Agemo, we built the brand voice for a GenAI product that had no precedent to sound like.",
   "tags": [
    "brand voice",
    "client work"
   ],
   "url": "/work/agemo/brand-voice.html",
   "have": "none",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "agemo/brand-voice",
   "clientSlug": "agemo"
  },
  {
   "pill": "web",
   "client": "EWC",
   "piece": "website",
   "s": "For East West [EWC], we designed and built the website and the funnel behind it, with the artifacts a visitor needs on the way to a yes.",
   "tags": [
    "website",
    "funnel",
    "client work"
   ],
   "url": "/work/ewc/website.html",
   "have": "none",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "ewc/website",
   "clientSlug": "ewc"
  },
  {
   "pill": "web",
   "client": "Klydo",
   "piece": "product",
   "s": "For Klydo, we designed the product that carried the 15-minute promise from a pitch deck to a million orders.",
   "tags": [
    "product",
    "client work"
   ],
   "url": "/work/klydo/product.html",
   "have": "partial",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "klydo/product",
   "clientSlug": "klydo"
  },
  {
   "pill": "web",
   "client": "Agemo / Codewords",
   "piece": "product design",
   "s": "For Agemo, we drew eight hypotheses twenty-six times to find the interface for a GenAI product nobody had seen before.",
   "tags": [
    "product design",
    "research",
    "client work"
   ],
   "url": "/work/agemo/product-design.html",
   "have": "page",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "agemo/product-design",
   "clientSlug": "agemo"
  },
  {
   "pill": "web",
   "client": "Klydo",
   "piece": "design",
   "s": "For Klydo, we ran design across 120 days and 30 artifacts, from the packaging to the app.",
   "tags": [
    "design",
    "client work"
   ],
   "url": "/work/klydo/design.html",
   "have": "page",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "klydo/design",
   "clientSlug": "klydo"
  },
  {
   "pill": "web",
   "client": "Tatsam",
   "piece": "product",
   "s": "For Tatsam, we designed the product that turned a wellbeing philosophy into something a team could use every week.",
   "tags": [
    "product",
    "client work"
   ],
   "url": "/work/tatsam/product.html",
   "have": "page",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "tatsam/product",
   "clientSlug": "tatsam"
  },
  {
   "pill": "web",
   "client": "ConveGenius",
   "piece": "gamification",
   "s": "For ConveGenius, we turned a request for a rewards layer into a gamification system grounded in what students actually do.",
   "tags": [
    "gamification",
    "product",
    "client work"
   ],
   "url": "/work/convegenius/gamification.html",
   "have": "page",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "convegenius/gamification",
   "clientSlug": "convegenius"
  },
  {
   "pill": "web",
   "client": "Shapeshifter",
   "piece": "AI system + automation",
   "s": "For Shapeshifter, we built the AI system that turns a conversation into a proposal, and the automation around it.",
   "tags": [
    "AI system",
    "automation",
    "client work"
   ],
   "url": "/work/shapeshifter/ai-system.html",
   "have": "none",
   "to": "piece",
   "clientPage": false,
   "soon": false,
   "slug": "shapeshifter/ai-system",
   "clientSlug": "shapeshifter"
  },
  {
   "pill": "web",
   "client": "Rachna Nivas",
   "piece": "website (soon)",
   "s": "For Rachna Nivas, we're building the website that carries a Kathak soloist's work beyond the studio.",
   "tags": [
    "website",
    "client work",
    "soon"
   ],
   "url": "/work/rachna-nivas/website.html",
   "have": "none",
   "to": "piece",
   "clientPage": true,
   "soon": true,
   "slug": "rachna-nivas/website",
   "clientSlug": "rachna-nivas"
  },
  {
   "pill": "strategy",
   "client": "Pratham USA",
   "piece": "reactivation & retention strategy",
   "s": "For Pratham USA, we worked out why donors give once and stop, and designed the strategy to bring them back and keep them.",
   "tags": [
    "retention",
    "strategy",
    "client work"
   ],
   "url": "/work/pratham/retention-strategy.html",
   "have": "page",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "pratham/retention-strategy",
   "clientSlug": "pratham"
  },
  {
   "pill": "strategy",
   "client": "Klydo",
   "piece": "strategy",
   "s": "For Klydo, we ran the leadership offsite that found the thesis underneath the delivery channel.",
   "tags": [
    "strategy",
    "offsite",
    "client work"
   ],
   "url": "/work/klydo/strategy.html",
   "have": "page",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "klydo/strategy",
   "clientSlug": "klydo"
  },
  {
   "pill": "strategy",
   "client": "Pratham USA",
   "piece": "donor research",
   "s": "For Pratham USA, we mapped the donor journey and audited every touchpoint to find where to invest next.",
   "tags": [
    "research",
    "service design",
    "client work"
   ],
   "url": "/work/pratham/donor-research.html",
   "have": "page",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "pratham/donor-research",
   "clientSlug": "pratham"
  },
  {
   "pill": "strategy",
   "client": "Klydo",
   "piece": "pivot support",
   "s": "For Klydo, we stayed through the pivot, helping the team decide what to keep and what to let go.",
   "tags": [
    "pivot support",
    "client work"
   ],
   "url": "/work/klydo/pivot-support.html",
   "have": "partial",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "klydo/pivot-support",
   "clientSlug": "klydo"
  },
  {
   "pill": "strategy",
   "client": "ConveGenius",
   "piece": "strategy",
   "s": "For ConveGenius, we set the strategy that decided what the rewards layer was actually for.",
   "tags": [
    "strategy",
    "client work"
   ],
   "url": "/work/convegenius/strategy.html",
   "have": "partial",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "convegenius/strategy",
   "clientSlug": "convegenius"
  },
  {
   "pill": "strategy",
   "client": "Agemo / Codewords",
   "piece": "product strategy",
   "s": "For Agemo, we set the product strategy for a GenAI startup with nothing to copy.",
   "tags": [
    "product strategy",
    "client work"
   ],
   "url": "/work/agemo/product-strategy.html",
   "have": "partial",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "agemo/product-strategy",
   "clientSlug": "agemo"
  },
  {
   "pill": "strategy",
   "client": "Klydo",
   "piece": "marketing",
   "s": "For Klydo, we ran marketing as experiments, three Instagram tests in fourteen days, to learn what the brand could say.",
   "tags": [
    "marketing",
    "experiments",
    "client work"
   ],
   "url": "/work/klydo/marketing.html",
   "have": "partial",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "klydo/marketing",
   "clientSlug": "klydo"
  },
  {
   "pill": "strategy",
   "client": "Rachna Nivas",
   "piece": "consulting",
   "s": "For Rachna Nivas, we spent nine months of strategic coaching giving her work a form that could leave the studio with her.",
   "tags": [
    "consulting",
    "coaching",
    "client work"
   ],
   "url": "/work/rachna-nivas/consulting.html",
   "have": "page",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "rachna-nivas/consulting",
   "clientSlug": "rachna-nivas"
  },
  {
   "pill": "story",
   "client": "TomboyX",
   "piece": "investor storytelling",
   "s": "For TomboyX, we rewrote the story of a beloved underwear brand for three different investor rooms, in a down round.",
   "tags": [
    "investor storytelling",
    "client work"
   ],
   "url": "/work/tomboyx/investor-storytelling.html",
   "have": "page",
   "to": "piece",
   "clientPage": false,
   "soon": false,
   "slug": "tomboyx/investor-storytelling",
   "clientSlug": "tomboyx"
  },
  {
   "pill": "story",
   "client": "Rachna Nivas",
   "piece": "brand storytelling",
   "s": "For Rachna Nivas, we found the story of a Kathak soloist's work so her photographers, editors and apprentices could carry it.",
   "tags": [
    "brand storytelling",
    "client work"
   ],
   "url": "/work/rachna-nivas/brand-storytelling.html",
   "have": "page",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "rachna-nivas/brand-storytelling",
   "clientSlug": "rachna-nivas"
  },
  {
   "pill": "story",
   "client": "EWC",
   "piece": "branding storytelling",
   "s": "For East West [EWC], we wrote the brand story that the website and the funnel are built on.",
   "tags": [
    "brand storytelling",
    "client work"
   ],
   "url": "/work/ewc/brand-story.html",
   "have": "none",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "ewc/brand-story",
   "clientSlug": "ewc"
  },
  {
   "pill": "story",
   "client": "Klydo",
   "piece": "storytelling",
   "s": "For Klydo, we wrote the story the team told itself, then investors, then a million customers.",
   "tags": [
    "storytelling",
    "client work"
   ],
   "url": "/work/klydo/storytelling.html",
   "have": "partial",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "klydo/storytelling",
   "clientSlug": "klydo"
  },
  {
   "pill": "story",
   "client": "Tatsam",
   "piece": "pitch",
   "s": "For Tatsam, we built the pitch: the research, the brand and the product told as one argument.",
   "tags": [
    "pitch",
    "storytelling",
    "client work"
   ],
   "url": "/work/tatsam/pitch.html",
   "have": "page",
   "to": "piece",
   "clientPage": true,
   "soon": false,
   "slug": "tatsam/pitch",
   "clientSlug": "tatsam"
  },
  {
   "pill": "exp",
   "client": "Metro Museum of the Forgotten",
   "piece": "game",
   "s": "For ourselves, we built a museum of things people left on the Delhi Metro, as a game, from the real lost-and-found records.",
   "tags": [
    "artistic project",
    "game",
    "data"
   ],
   "url": "/experiments/metro-museum.html",
   "have": "none",
   "to": "experiment",
   "clientPage": false,
   "soon": false,
   "slug": "metro-museum",
   "clientSlug": null
  },
  {
   "pill": "exp",
   "client": "Poetic lineage explorer",
   "piece": "tool",
   "s": "For a demo, we built a poetic lineage explorer that traces who a poem learned from.",
   "tags": [
    "personal exploration",
    "tool"
   ],
   "url": "/experiments/poetic-lineage.html",
   "have": "none",
   "to": "experiment",
   "clientPage": false,
   "soon": false,
   "slug": "poetic-lineage",
   "clientSlug": null
  },
  {
   "pill": "exp",
   "client": "Comics",
   "piece": "comics",
   "s": "For ourselves, we make comics: Kahran writes the storylines, Divya draws them.",
   "tags": [
    "artistic project",
    "comics"
   ],
   "url": "/experiments/comics.html",
   "have": "page",
   "to": "experiment",
   "clientPage": false,
   "soon": false,
   "slug": "comics",
   "clientSlug": null
  },
  {
   "pill": "exp",
   "client": "Projection mapper",
   "piece": "tool",
   "s": "For a demo, we built a projection mapper to throw drawings onto real rooms.",
   "tags": [
    "personal exploration",
    "tool"
   ],
   "url": "/experiments/projection-mapper.html",
   "have": "none",
   "to": "experiment",
   "clientPage": false,
   "soon": false,
   "slug": "projection-mapper",
   "clientSlug": null
  },
  {
   "pill": "exp",
   "client": "AI videos for poetry",
   "piece": "film",
   "s": "For ourselves, we turn poems into video with AI, one poem at a time.",
   "tags": [
    "artistic project",
    "film"
   ],
   "url": "/experiments/ai-poetry-videos.html",
   "have": "none",
   "to": "experiment",
   "clientPage": false,
   "soon": false,
   "slug": "ai-poetry-videos",
   "clientSlug": null
  },
  {
   "pill": "exp",
   "client": "Brand Studio",
   "piece": "tool",
   "s": "For a demo, we built Brand Studio, [what it does, in one clause].",
   "tags": [
    "personal exploration",
    "tool"
   ],
   "url": "/experiments/brand-studio.html",
   "have": "none",
   "to": "experiment",
   "clientPage": false,
   "soon": false,
   "slug": "brand-studio",
   "clientSlug": null
  },
  {
   "pill": "exp",
   "client": "Art stager",
   "piece": "tool",
   "s": "For a demo, we built Art Stager, [what it does, in one clause].",
   "tags": [
    "personal exploration",
    "tool"
   ],
   "url": "/experiments/art-stager.html",
   "have": "none",
   "to": "experiment",
   "clientPage": false,
   "soon": false,
   "slug": "art-stager",
   "clientSlug": null
  },
  {
   "pill": "exp",
   "client": "AI personal automation",
   "piece": "tool",
   "s": "For ourselves, we built a personal AI automation [for ADHD: what it does, in one clause].",
   "tags": [
    "personal exploration",
    "automation"
   ],
   "url": "/experiments/personal-automation.html",
   "have": "none",
   "to": "experiment",
   "clientPage": false,
   "soon": false,
   "slug": "personal-automation",
   "clientSlug": null
  },
  {
   "pill": "exp",
   "client": "Line before",
   "piece": "?",
   "s": "For ourselves, we made Line Before, [what it is, in one clause].",
   "tags": [
    "artistic project"
   ],
   "url": "/experiments/line-before.html",
   "have": "none",
   "to": "experiment",
   "clientPage": false,
   "soon": false,
   "slug": "line-before",
   "clientSlug": null
  },
  {
   "pill": "exp",
   "client": "Everything Bazaar",
   "piece": "advertising research",
   "s": "For ourselves, we invented five brands and art-directed a billboard for each, one still at a time, in Blender.",
   "tags": [
    "artistic project",
    "research"
   ],
   "url": "/experiments/everything-bazaar.html",
   "have": "none",
   "to": "experiment",
   "clientPage": false,
   "soon": false,
   "slug": "everything-bazaar",
   "clientSlug": null
  }
 ],
 "clients": {
  "klydo": {
   "slug": "klydo",
   "name": "Klydo",
   "pieces": [
    "klydo/branding",
    "klydo/product",
    "klydo/design",
    "klydo/strategy",
    "klydo/pivot-support",
    "klydo/marketing",
    "klydo/storytelling"
   ],
   "page": true,
   "line": "From four people to a million orders to a thesis.",
   "who": "15-minute fashion delivery, India",
   "since": "September 2025",
   "chapters": [
    {
     "no": "01",
     "name": "The build",
     "span": "Sep 2025 – Jan 2026",
     "pieces": [
      "klydo/design",
      "klydo/product",
      "klydo/branding",
      "klydo/storytelling"
     ]
    },
    {
     "no": "02",
     "name": "The shift",
     "span": "2026 · [month of the offsite]",
     "gap": "eight months in",
     "pieces": [
      "klydo/strategy",
      "klydo/marketing",
      "klydo/pivot-support"
     ]
    }
   ],
   "when": {
    "klydo/design": "10 Sep 2025 – 7 Jan 2026",
    "klydo/product": "14 Sep – 14 Dec 2025",
    "klydo/branding": "24 Sep – 26 Nov 2025",
    "klydo/storytelling": "26 Dec 2025 · [the rest undated]",
    "klydo/strategy": "2026 · \"eight months in\"",
    "klydo/marketing": "the 14 days after the offsite",
    "klydo/pivot-support": "after the offsite · [dates]"
   }
  },
  "secret-senses": {
   "slug": "secret-senses",
   "name": "Secret Senses",
   "pieces": [
    "secret-senses/identity-packaging"
   ],
   "page": false
  },
  "tatsam": {
   "slug": "tatsam",
   "name": "Tatsam",
   "pieces": [
    "tatsam/brand",
    "tatsam/product",
    "tatsam/pitch"
   ],
   "page": true
  },
  "gliitch": {
   "slug": "gliitch",
   "name": "Gliitch",
   "pieces": [
    "gliitch/identity"
   ],
   "page": false
  },
  "xtdb": {
   "slug": "xtdb",
   "name": "XTDB",
   "pieces": [
    "xtdb/visual-identity"
   ],
   "page": false
  },
  "agemo": {
   "slug": "agemo",
   "name": "Agemo",
   "pieces": [
    "agemo/brand-voice",
    "agemo/product-design",
    "agemo/product-strategy"
   ],
   "page": true
  },
  "ewc": {
   "slug": "ewc",
   "name": "EWC",
   "pieces": [
    "ewc/website",
    "ewc/brand-story"
   ],
   "page": true
  },
  "convegenius": {
   "slug": "convegenius",
   "name": "ConveGenius",
   "pieces": [
    "convegenius/gamification",
    "convegenius/strategy"
   ],
   "page": true
  },
  "shapeshifter": {
   "slug": "shapeshifter",
   "name": "Shapeshifter",
   "pieces": [
    "shapeshifter/ai-system"
   ],
   "page": false
  },
  "rachna-nivas": {
   "slug": "rachna-nivas",
   "name": "Rachna Nivas",
   "pieces": [
    "rachna-nivas/website",
    "rachna-nivas/consulting",
    "rachna-nivas/brand-storytelling"
   ],
   "page": true
  },
  "pratham": {
   "slug": "pratham",
   "name": "Pratham USA",
   "pieces": [
    "pratham/retention-strategy",
    "pratham/donor-research"
   ],
   "page": true
  },
  "tomboyx": {
   "slug": "tomboyx",
   "name": "TomboyX",
   "pieces": [
    "tomboyx/investor-storytelling"
   ],
   "page": false
  }
 },
 "stage": {
  "metro-museum": {
   "kind": "playable",
   "note": "the web build · URL not found yet",
   "keys": "WASD walk · mouse look · E attend to a glowing item"
  },
  "poetic-lineage": {
   "kind": "playable",
   "note": "the tool · [hosted?]"
  },
  "comics": {
   "kind": "reader",
   "note": "the first page; the reader is at /comics/"
  },
  "projection-mapper": {
   "kind": "video",
   "note": "a video of it on a real wall"
  },
  "ai-poetry-videos": {
   "kind": "video",
   "note": "a poem film"
  },
  "brand-studio": {
   "kind": "unknown",
   "note": "[what it is: open question 3]"
  },
  "art-stager": {
   "kind": "unknown",
   "note": "[what it is: open question 3]"
  },
  "personal-automation": {
   "kind": "video",
   "note": "screens or a video; it runs on private data"
  },
  "line-before": {
   "kind": "installation",
   "note": "The Line Before, an installation · divya.studiotypo.xyz"
  },
  "everything-bazaar": {
   "kind": "stills",
   "note": "a chosen set of stills · needs Divya; the board site is local-only"
  }
 },
 "facts": {
  "klydo/branding": [
   [
    "when",
    "September – November 2025"
   ],
   [
    "rounds",
    "5, oldest first"
   ]
  ],
  "metro-museum": [
   [
    "made by",
    "[who: Divya? both?]"
   ],
   [
    "since",
    "July 2026"
   ],
   [
    "status",
    "in progress · a Steam build began 30 Sep 2026"
   ]
  ]
 }
};
globalThis.slugTag = (t) => t.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
globalThis.pieceHref = (p) => (p.pill === 'exp' ? 'experiment.html?p=' : 'piece.html?p=') + p.slug;
globalThis.clientHref = (c) => { const cl = SITE.clients[c]; return cl.page ? 'client.html?c=' + c : pieceHref(SITE.pieces.find(p => p.slug === cl.pieces[0])); };
globalThis.pillName = (id) => SITE.pills.find(p => p.id === id).label;
globalThis.esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;');
if (typeof module !== 'undefined') module.exports = globalThis.SITE;
