// Writes site/site-data.js: everything the prototype's
// templates read. Generated pieces + clients (from Study 07's data), plus the
// few hand facts earlier studies established, each tagged with its study.
const fs = require('fs');
// run from the repo: node studies/iterations/12/build-data.cjs  (writes site/site-data.js)
const path = require('path');
const out = path.join(__dirname, 'site');
const { WORK } = require('../07/work-data.js');
const pieces = WORK.pieces.map(p => { const slug = p.url.match(/^\/(work|experiments)\/(.+)\.html$/)[2]; return { ...p, slug, clientSlug: p.pill === 'exp' ? null : slug.split('/')[0] }; });
const clients = {};
pieces.filter(p => p.clientSlug).forEach(p => (clients[p.clientSlug] = clients[p.clientSlug] || { slug: p.clientSlug, name: p.client.split(' / ')[0], pieces: [] }).pieces.push(p.slug));
Object.values(clients).forEach(c => c.page = c.pieces.length >= 2); // Study 06
const d = { pills: WORK.pills, pieces, clients };
// Study 06: Klydo's facts and the start dates the wall proves
const clientFacts = {
  klydo: { line: 'From four people to a million orders to a thesis.', who: '15-minute fashion delivery, India', since: 'September 2025',
    chapters: [{ no: '01', name: 'The build', span: 'Sep 2025 – Jan 2026', pieces: ['klydo/design', 'klydo/product', 'klydo/branding', 'klydo/storytelling'] },
               { no: '02', name: 'The shift', span: '2026 · [month of the offsite]', gap: 'eight months in', pieces: ['klydo/strategy', 'klydo/marketing', 'klydo/pivot-support'] }],
    when: { 'klydo/design': '10 Sep 2025 – 7 Jan 2026', 'klydo/product': '14 Sep – 14 Dec 2025', 'klydo/branding': '24 Sep – 26 Nov 2025', 'klydo/storytelling': '26 Dec 2025 · [the rest undated]', 'klydo/strategy': '2026 · "eight months in"', 'klydo/marketing': 'the 14 days after the offsite', 'klydo/pivot-support': 'after the offsite · [dates]' } },
};
// Study 05: what each experiment's stage holds
const stage = {
  'metro-museum': { kind: 'playable', note: 'the web build · URL not found yet', keys: 'WASD walk · mouse look · E attend to a glowing item' },
  'poetic-lineage': { kind: 'playable', note: 'the tool · [hosted?]' },
  'comics': { kind: 'reader', note: 'the first page; the reader is at /comics/' },
  'projection-mapper': { kind: 'video', note: 'a video of it on a real wall' },
  'ai-poetry-videos': { kind: 'video', note: 'a poem film' },
  'brand-studio': { kind: 'unknown', note: '[what it is: open question 3]' },
  'art-stager': { kind: 'unknown', note: '[what it is: open question 3]' },
  'personal-automation': { kind: 'video', note: 'screens or a video; it runs on private data' },
  'line-before': { kind: 'installation', note: 'The Line Before, an installation · divya.studiotypo.xyz' },
  'everything-bazaar': { kind: 'stills', note: 'a chosen set of stills · needs Divya; the board site is local-only' },
};
// Study 04 / 05: facts lines for the two pieces whose material we have
const facts = {
  'klydo/branding': [['when', 'September – November 2025'], ['rounds', '5, oldest first']],
  'metro-museum': [['made by', '[who: Divya? both?]'], ['since', 'July 2026'], ['status', 'in progress · a Steam build began 30 Sep 2026']],
};
Object.entries(clientFacts).forEach(([k, v]) => Object.assign(d.clients[k], v));
const js = `// Generated by build-data.cjs from Study 07's work-data.js, plus hand facts
// from Studies 04 (Klydo · branding), 05 (experiment stages, Metro Museum) and
// 06 (Klydo's client page). The prototype's templates read only this and rounds.js.
globalThis.SITE = ${JSON.stringify({ pills: d.pills, pieces: d.pieces, clients: d.clients, stage, facts }, null, 1)};
globalThis.slugTag = (t) => t.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
globalThis.pieceHref = (p) => (p.pill === 'exp' ? 'experiment.html?p=' : 'piece.html?p=') + p.slug;
globalThis.clientHref = (c) => { const cl = SITE.clients[c]; return cl.page ? 'client.html?c=' + c : pieceHref(SITE.pieces.find(p => p.slug === cl.pieces[0])); };
globalThis.pillName = (id) => SITE.pills.find(p => p.id === id).label;
globalThis.esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;');
if (typeof module !== 'undefined') module.exports = globalThis.SITE;
`;
fs.writeFileSync(out + '/site-data.js', js);
console.log('ok', d.pieces.length, Object.keys(d.clients).length);
